-- Sample blog posts for testing
-- Run this after creating the schema

-- Insert sample blog posts
INSERT INTO public.blog_posts (
  slug,
  title,
  excerpt,
  content,
  author_name,
  author_image,
  published_date,
  read_time,
  cover_image,
  tags,
  category,
  seo_title,
  seo_description,
  published
) VALUES
(
  'why-tech-certifications-matter',
  'Why Tech Certifications Matter More Than Ever',
  'Discover how certifications can accelerate your career in Africa''s growing tech industry',
  '<p>In today''s competitive tech landscape, having the right certifications can make all the difference in your career trajectory. For professionals across Africa, tech certifications represent more than just credentials—they''re gateways to global opportunities.</p><p><strong>The Value Proposition</strong></p><p>Tech certifications provide structured learning paths that combine theoretical knowledge with practical skills. Unlike traditional degrees, they can be completed in months rather than years, making them ideal for career switchers and professionals looking to upskill quickly.</p><p><strong>Industry Recognition</strong></p><p>Major tech companies like Google, Microsoft, and AWS actively recognize and value these certifications. Many hiring managers specifically look for certified professionals because they know these individuals have validated, up-to-date skills.</p><p><strong>Career Advancement</strong></p><p>Studies show that certified professionals often command higher salaries and have more job opportunities. In Africa''s tech market, where skilled talent is in high demand, certifications can be the differentiator that lands you your dream job.</p>',
  'Sarah Johnson',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
  '2024-01-15',
  8,
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=600&fit=crop',
  ARRAY['Certifications', 'Career', 'Learning'],
  'Career',
  'Why Tech Certifications Matter More Than Ever in 2024',
  'Learn how tech certifications can accelerate your career in Africa''s growing tech industry. Expert insights and practical advice.',
  true
),
(
  'google-career-certificates-guide',
  'Complete Guide to Google Career Certificates',
  'Everything you need to know about Google''s professional certificate programs',
  '<p>Google Career Certificates have revolutionized professional development by offering high-quality, job-ready training that doesn''t require a degree. Here''s your comprehensive guide.</p><p><strong>Available Programs</strong></p><p>Google offers certificates in Data Analytics, Project Management, UX Design, IT Support, Digital Marketing & E-commerce, and more. Each program is designed with input from industry experts.</p><p><strong>Learning Format</strong></p><p>The programs are entirely online and self-paced. Most can be completed in 3-6 months with 10 hours of study per week. The courses include video lectures, hands-on projects, and assessments.</p><p><strong>Career Support</strong></p><p>Certificate holders get access to Google''s employer consortium, which includes over 150 employers actively seeking certified professionals. You''ll also receive resume help and interview preparation.</p><p><strong>Cost and Accessibility</strong></p><p>Programs cost around $39/month on Coursera, with financial aid available. For African learners, this represents incredible value for globally recognized credentials.</p>',
  'Michael Chen',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  '2024-01-10',
  12,
  'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=1200&h=600&fit=crop',
  ARRAY['Google', 'Certifications', 'Career', 'Guide'],
  'Certifications',
  'Complete Guide to Google Career Certificates 2024',
  'Everything you need to know about Google professional certificate programs, costs, and career opportunities.',
  true
),
(
  'learning-cloud-computing',
  'Getting Started with Cloud Computing',
  'Your roadmap to becoming a cloud professional in 2024',
  '<p>Cloud computing is one of the fastest-growing sectors in tech, and the demand for cloud professionals far exceeds supply. Here''s how to get started.</p><p><strong>Understanding Cloud Platforms</strong></p><p>The big three cloud providers—AWS, Microsoft Azure, and Google Cloud—dominate the market. Each offers unique strengths, but learning any one of them gives you transferable skills.</p><p><strong>Starting Point</strong></p><p>Begin with foundational concepts: virtualization, networking, storage, and security. The AWS Cloud Practitioner or Azure Fundamentals certifications are excellent entry points.</p><p><strong>Hands-On Practice</strong></p><p>Theory alone won''t cut it. Use free tiers from cloud providers to build projects. Create a website, set up databases, or deploy applications. This practical experience is invaluable.</p><p><strong>Career Paths</strong></p><p>Cloud careers include Solutions Architect, DevOps Engineer, Cloud Security Specialist, and more. Each path requires different skills, so research which aligns with your interests.</p>',
  'David Okonkwo',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
  '2024-01-05',
  10,
  'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=600&fit=crop',
  ARRAY['Cloud Computing', 'AWS', 'Azure', 'Tutorial'],
  'Tutorials',
  'Getting Started with Cloud Computing: Complete Beginner''s Guide',
  'Learn how to start your cloud computing career with this comprehensive roadmap for 2024.',
  true
),
(
  'african-tech-ecosystem-2024',
  'The Rise of Africa''s Tech Ecosystem',
  'How African tech is reshaping the global innovation landscape',
  '<p>Africa''s tech ecosystem is experiencing unprecedented growth, attracting billions in investment and producing world-class innovations. Here''s what''s driving this transformation.</p><p><strong>Investment Boom</strong></p><p>Venture capital funding for African startups has grown exponentially, with countries like Nigeria, Kenya, and South Africa leading the charge. Fintech, agritech, and healthtech are particularly hot sectors.</p><p><strong>Talent Pipeline</strong></p><p>African developers and tech professionals are increasingly competitive on the global stage. Remote work has opened doors for African talent to work with companies worldwide while building local ecosystems.</p><p><strong>Innovation Hubs</strong></p><p>Cities like Lagos, Nairobi, and Cape Town have emerged as major tech hubs, with thriving startup communities, accelerators, and co-working spaces fostering collaboration and growth.</p><p><strong>Challenges and Opportunities</strong></p><p>While infrastructure and regulatory challenges remain, they also present opportunities for innovative solutions. The future of African tech is bright and full of potential.</p>',
  'Amara Nwosu',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
  '2024-01-20',
  7,
  'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=1200&h=600&fit=crop',
  ARRAY['Africa', 'Tech Ecosystem', 'Innovation', 'Startups'],
  'Industry',
  'The Rise of Africa''s Tech Ecosystem in 2024',
  'Explore how African tech is reshaping global innovation with record investments and world-class talent.',
  true
),
(
  'mastering-data-analytics',
  'Mastering Data Analytics: A Practical Guide',
  'Step-by-step guide to becoming a data analyst',
  '<p>Data analytics is one of the most in-demand skills across industries. This guide will walk you through the journey from beginner to job-ready analyst.</p><p><strong>Essential Skills</strong></p><p>Start with SQL for data querying, Excel for analysis, and basic statistics. Then add Python or R for advanced analytics and data visualization tools like Tableau or Power BI.</p><p><strong>Learning Path</strong></p><p>1. Foundations: Statistics, SQL, Excel<br>2. Programming: Python or R<br>3. Visualization: Tableau, Power BI<br>4. Advanced: Machine Learning basics<br>5. Practice: Build portfolio projects</p><p><strong>Portfolio Development</strong></p><p>Create 3-5 projects that showcase different skills. Analyze public datasets, build dashboards, and document your process. Share everything on GitHub and create a portfolio website.</p><p><strong>Job Search Strategy</strong></p><p>Target entry-level analyst roles, junior data scientist positions, or business intelligence roles. Tailor your resume to highlight relevant projects and certifications.</p>',
  'Lisa Banda',
  'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop',
  '2024-01-12',
  15,
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
  ARRAY['Data Analytics', 'Tutorial', 'Career', 'Python'],
  'Tutorials',
  'Mastering Data Analytics: Complete Practical Guide for 2024',
  'Step-by-step guide to becoming a professional data analyst with practical projects and career advice.',
  true
);
